add task 16
AndreyWild/hotel_tregulov pull request #2
Opened 2021-09-07 20:18 UTC by AndreyWild

2021-09-08 09:08 UTC, SenlaCoursesAdmin requested changes

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/api/controller/IGenericController.java
> +public interface IGenericController <T extends AEntity> {
IGenericController -> IController

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/api/dao/IGenericDao.java
> +public interface IGenericDao<T extends AEntity> {
аналогично

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +        ComboPooledDataSource dataSource = new ComboPooledDataSource(); // подключение к БД
ComboPooledDataSource почему этот интерфейс а не DataSource

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +            dataSource.setJdbcUrl("jdbc:mysql://localhost:3306/hotel?autoReconnect=true&useSSL=false&serverTimezone=UTC");
?autoReconnect=true&useSSL=false&serverTimezone=UTC" 
для чего это?

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/configuration/MyWebInitializer.java
> +        AbstractAnnotationConfigDispatcherServletInitializer {
для чего класс?

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/AbstractController.java
> +public class AbstractController<T extends AEntity> implements IGenericController<T> {
AController

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/AbstractController.java
> +public class AbstractController<T extends AEntity> implements IGenericController<T> {
а что ты этим классом добавил?

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +            throw  new NoSuchEntityException("There is no Guest with ID = " + id + " in Database");
это в сервисах

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        guest.setAge(guestDto.getAge());
в сервисах

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return guestDto;
в сервисах

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        }
в сервисах

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/dao/AbstractDao.java
> +public abstract class AbstractDao<T extends AEntity> implements IGenericDao<T> {
ADao

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/exceptions/EntityIncorrectData.java
> +public class EntityIncorrectData {
что это за класс?

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/exceptions/EntityExceptionGlobalHandler.java
> +        return new ResponseEntity<>(data, HttpStatus.BAD_REQUEST);
у тебя разные возвраты это  ResponseEntity а контроллеры обьекты возвращают хорошо ли это?

2021-09-08 09:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/exceptions/NoSuchEntityException.java
> +public class NoSuchEntityException extends RuntimeException {
почему от RuntimeException а не Exception

2021-09-09 18:02 UTC, AndreyWild commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +            dataSource.setJdbcUrl("jdbc:mysql://localhost:3306/hotel?autoReconnect=true&useSSL=false&serverTimezone=UTC");
autoReconnect=true - реконнект при обрыве связи,
useSSL=false - без шифрования
serverTimezone=UTC - часовой пояс, у меня кстати иногда траблы с MySQL сервером бывают из за того что время расходится

2021-09-09 18:04 UTC, AndreyWild commented on src/main/java/com/senla/hotel/configuration/MyWebInitializer.java
> +        AbstractAnnotationConfigDispatcherServletInitializer {
Заменяет файл web.xml, на лекции тож его упоминали.

2021-09-09 18:05 UTC, AndreyWild commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        }
Эта ошибка которая выводится преобразуется в json и выводится в браузер.

2021-09-09 18:06 UTC, AndreyWild commented on src/main/java/com/senla/hotel/api/dao/IGenericDao.java
> +public interface IGenericDao<T extends AEntity> {
Нейминг конвеншн не нарушен, чем больше слов тем понятнее =)

2021-09-09 18:06 UTC, AndreyWild commented on src/main/java/com/senla/hotel/api/controller/IGenericController.java
> +public interface IGenericController <T extends AEntity> {
Вообще удалю, т.к. не придумал как Generic Controller не придумал как реализовать

2021-09-09 18:07 UTC, AndreyWild commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +        ComboPooledDataSource dataSource = new ComboPooledDataSource(); // подключение к БД
Это пул соединений библиотеки c3p0, она контролирует пул соединений.

2021-09-09 18:13 UTC, AndreyWild commented on src/main/java/com/senla/hotel/exceptions/EntityIncorrectData.java
> +public class EntityIncorrectData {
Этот класс принимает сообщение исключений и передает его в EntityExceptionGlobalHandler, там сообщение преобразуется в json и отображается клиенту.

2021-09-09 18:14 UTC, AndreyWild commented on src/main/java/com/senla/hotel/exceptions/EntityExceptionGlobalHandler.java
> +        return new ResponseEntity<>(data, HttpStatus.BAD_REQUEST);
Не понял тебя.

2021-09-09 18:14 UTC, AndreyWild commented on src/main/java/com/senla/hotel/exceptions/NoSuchEntityException.java
> +public class NoSuchEntityException extends RuntimeException {
К сожалению не знаю, такой была реализация которую я нашел.

2021-09-09 19:17 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +        ComboPooledDataSource dataSource = new ComboPooledDataSource(); // подключение к БД
а почему именно c3p0?

2021-09-09 19:18 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        }
эту проверку делают в сервисах а не в котнроллере

2021-09-09 19:19 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/exceptions/NoSuchEntityException.java
> +public class NoSuchEntityException extends RuntimeException {
почитай теорию на этот счет и ответь пожалуйста мне

2021-09-10 06:26 UTC, AndreyWild commented on src/main/java/com/senla/hotel/configuration/MyConfig.java
> +        ComboPooledDataSource dataSource = new ComboPooledDataSource(); // подключение к БД
c3p0 — ещё одна библиотека для создания пулов соединений. От HikariCP её отличает встроенная поддержка кэширования запросов, которая позволяет автоматически переиспользовать prepared statements, увеличивая тем самым производительность.

2021-09-10 06:36 UTC, AndreyWild commented on src/main/java/com/senla/hotel/exceptions/NoSuchEntityException.java
> +public class NoSuchEntityException extends RuntimeException {
В оракловской доке все примеры NoSuchEntityException наследуются от RuntimeException, конечно между ними еще бывает класс ошибок сервиса или базы данных.

2021-09-10 12:59 UTC, SenlaCoursesAdmin requested changes
где-то дто где-то обьект надо одно везде возвращать

2021-09-10 12:59 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/RoomController.java
> +    @GetMapping("/rooms")
в одном месте указывается

2021-09-10 12:59 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/RoomController.java
> +        }
проверка дб в сервисах

2021-09-14 05:07 UTC, SenlaCoursesAdmin requested changes

2021-09-14 05:07 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return modelMapper.map(guestService.getById(id), GuestDto.class);
маппируют на уровне сервисов

2021-09-14 05:07 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/dto/OrderDto.java
> +    private Long guest;
guestId

2021-09-14 05:07 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/model/entities/Guest.java
> +    @Column(name = "name")
если одинаковое можно не писать имя

2021-09-14 17:58 UTC, AndreyWild commented on src/main/java/com/senla/hotel/model/entities/Guest.java
> +    @Column(name = "name")
Я знаю, я явно прописал имя столбца для лучшей читаемости кода =)

2021-09-14 17:58 UTC, AndreyWild commented on src/main/java/com/senla/hotel/dto/OrderDto.java
> +    private Long guest;
Это я заменю на сущность GuestDto

2021-09-14 17:58 UTC, AndreyWild commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return modelMapper.map(guestService.getById(id), GuestDto.class);
ok

2021-09-15 06:08 UTC, SenlaCoursesAdmin requested changes

2021-09-15 06:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        log.info("Received request (GET): /guests");
лог тут не нужен

2021-09-15 06:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return ResponseEntity.noContent().build();
в чем разница от сейва?

2021-09-15 06:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/OrderController.java
> +        return "Order with ID = " + id + " was deleted";
return void

2021-09-15 06:08 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/dto/OrderDto.java
> +    private RoomDto room;
RoomDto roomDto

2021-09-15 06:38 UTC, AndreyWild commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        log.info("Received request (GET): /guests");
на практическом сказали что принято писать логи в методах контроллеров

2021-09-15 06:39 UTC, AndreyWild commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return ResponseEntity.noContent().build();
в том что save работает, а add показывали на практическом и он не работает, но попробовать его надо было =)

2021-09-15 06:39 UTC, AndreyWild commented on src/main/java/com/senla/hotel/controller/OrderController.java
> +        return "Order with ID = " + id + " was deleted";
это обязательно?

2021-09-16 04:48 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        return ResponseEntity.noContent().build();
удаляем

2021-09-16 04:48 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/GuestController.java
> +        log.info("Received request (GET): /guests");
ок

2021-09-16 04:48 UTC, SenlaCoursesAdmin commented on src/main/java/com/senla/hotel/controller/OrderController.java
> +        return "Order with ID = " + id + " was deleted";
но не стрингу же

2021-09-16 04:49 UTC, SenlaCoursesAdmin approved these changes

2021-09-16 12:34 UTC, merged